import Header from "@/components/Header";
import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Next Crud",
  description: "Generated by create next app",
};

const RootLayout = ({ children }) => {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="p-4">
          <div className="max-w-4xl mx-auto">
            <Header></Header>
            {children}
          </div>
        </div>
      </body>
    </html>
  );
};

export default RootLayout;
